name: oras-setup
description: Setup ORAS CLI on GitHub Actions runners
branding:
  icon: box
  color: blue
inputs:
  version:
    description: Version of the official ORAS CLI to install
    required: false
    default: 1.2.0
  checksum:
    description: SHA256 of the customized ORAS CLI. Required if 'url' is present.
    required: false
  force:
    description: Force installation or upgrade of ORAS even if it is already installed
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Oras
      shell: bash
      run: |
        install_oras=0
        if command -v oras; then install_oras=1; fi
        if [[ -n "${{ inputs.force }}" ]]; then install_oras=0; fi

        tar_file=oras_${{ inputs.version }}_linux_amd64.tar.gz
        github_url="https://github.com/oras-project/oras/releases/download"

        curl -sL "${github_url}/v${{ inputs.version }}/${tar_file}" -o ./$tar_file
        curl -sL "${github_url}/v${{ inputs.version }}/oras_${{ inputs.version }}_checksums.txt" -o ./checksums.txt

        oras_checksum=$(cat checksums.txt | grep $tar_file | awk '{print $1}')

        if [[ ! "$(cat ./$tar_file | sha256sum)" != "$oras_checksum" ]]; then
          echo "Oras checksum not matching ..."
          exit 1
        fi

        mkdir -p oras-install/
        tar -zxf $tar_file -C oras-install/
        sudo mv oras-install/oras /usr/local/bin/
        rm -rf $tar_file oras-install/

        oras --version
