name: Test Artefact Actions (S3)

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-artefact-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Launch MinIO
        run: |
          docker run --rm -e MINIO_ROOT_USER=minioadmin -e MINIO_ROOT_PASSWORD=minioadmin -p 9000:9000 \
            -d minio/minio:latest minio server /data

      - name: Wait for MinIO to be ready
        run: |
          for i in {1..30}; do
            curl -s http://localhost:9000/minio/health/live && echo "MinIO is ready" && exit 0
            echo "Waiting for MinIO..."
            sleep 5
          done
          echo "MinIO did not become ready in time"
          exit 1

      - name: Install AWS Cli
        uses: dragoscirjan/github-tools/.github/actions/awscli-setup@main

      - name: Create Artefact
        run: |
          echo "hello world" > artefact.txt

      - name: Test aws s3 cp
        if: ${{ startsWith(matrix.registry, 's3://') }}
        run: |
          # set credentials
          aws configure set aws_access_key_id minioadmin
          aws configure set aws_secret_access_key minioadmin
          aws configure set default.region us-east-1
          aws configure set default.s3.endpoint_url http://localhost:9000
          # create s3 bucket
          aws s3 mb s3://artetact-bucket-test --endpoint-url http://localhost:9000
          # copy artefact to bucket
          aws s3 cp artefact.txt s3://artefact-test/artefact.txt --endpoint-url http://localhost:9000
          # list artefacts
          aws s3 ls s3://artefact-test/ --endpoint-url http://localhost:9000

      # - name: Test Artefact Push to ${{ matrix.registry }}
      #   uses: ./.github/actions/artefact-push
      #   with:
      #     to: ${{ matrix.registry }}
      #     artefact: artefact.txt
      #     version: 0.1.0
      #     username: ${{ matrix.username }}
      #     password: ${{ matrix.password }}
