name: Test Artifact Actions

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-docker:
    uses: dragoscirjan/github-tools/.github/workflows/test_artefact_actions-docker.yml@main
    secrets: inherit

  test-helm:
    uses: dragoscirjan/github-tools/.github/workflows/test_artefact_actions-helm.yml@main
    secrets: inherit

  test-oci:
    uses: dragoscirjan/github-tools/.github/workflows/test_artefact_actions-oci.yml@main
    secrets: inherit

  test-s3:
    uses: dragoscirjan/github-tools/.github/workflows/test_artefact_actions-s3.yml@main
    secrets: inherit
